nvim-telescope/telescope-file-browser.nvim

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser.lua
intertwined last commits accidentally..
> fix: trigger docs

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- scripts/gendocs.lua
Round 2 of #26
(See rationale for `fd` on original PR)
> feat: fd file and folder finders 

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
> fix: various doc issues and fd `add_dirs`

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/picker.lua
Try to clarify further and add more use cases upon reddit feedback.
> chore: refine workflow docs

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/picker.lua
update doc and comment
- create_file -> create
- open_file   -> open
> fix: doc of renamed fb_function

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/picker.lua
Fixes [reddit request](https://www.reddit.com/r/neovim/comments/sq6a95/change_folder_icon_color_in_telescopefilebrowser/)
> feat: expose dir icon hl

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser.lua
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
Inspired by https://github.com/nvim-telescope/telescope.nvim/pull/1847/files
Test driving how this looks in vimdocs (in hopes I've done it correctly ;)
> chore: clean up modules in docs

- lua/telescope/_extensions/file_browser/make_entry.lua
> fix(resume): reassign prompt buffer if invalid

- README.md
Clarification on keybindings for select/multi-select #185
> docs: add multi-select keybind info

- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
Closes #173 
@steve-numeus could you please verify this fixes the issue on your end?
> fix(actions.copy): disallow copying parent folder into dir

- lua/telescope/_extensions/file_browser/config.lua
> fix(hijack_netrw): no file_browser on :Explore

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
@rizo is this what you had in mind? :) testing welcome
Close #200
> feat(file_browser): automatically increase depth with auto_depth

- lua/telescope/_extensions/file_browser/make_entry.lua
Should fix #177 
@vignesh0025 apologies for the long wait, would you mind giving this a whirl? This should fix the underlying issue ideally in full.
E: After exhaustive testing, I think this works fine. We can always fix tiny problems later.
> fix(make_entry): show path_display properly

- lua/telescope/_extensions/file_browser/picker.lua
- lua/telescope/_extensions/file_browser/utils.lua
> fix: file_browser relative path handling

- lua/telescope/_extensions/file_browser/make_entry.lua
Closes #241 
@jamestrew could you please confirm this fixes the issue for you as well? :)
> fix(make_entry): adjust stat correctly on VimResized

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/fs_stat.lua
- lua/telescope/_extensions/file_browser/git.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/stats.lua
Tweak the passing of display items to enable individually highlighted entry items.
> multi-color entry display

- lua/telescope/_extensions/file_browser/utils.lua
> fix: verify given path exists

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/finders.lua
> feat(action): add toggle_respect_gitignore action

- lua/telescope/_extensions/file_browser/finders.lua
> fix: bad fd args to folder browser

- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/picker.lua
https://github.com/nvim-telescope/telescope-file-browser.nvim/assets/7228095/ef77f609-4e30-40ea-8d2b-02a9731353b3
Characters entered:
`config/ui/`
> Path separator opens directory when dir name is in input

- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/picker.lua
I found it very annoying to need to hit shift-enter instead of enter. So... Now you just need to hit enter and the prompt will get created.
> Autocreate prompt content if entry is nil

- .github/workflows/docgen.yml
- lua/telescope/_extensions/file_browser/actions.lua
does that help with docgen on PRs?
> chore: add pull request trigger for docgen

- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/make_entry_utils.lua
- lua/telescope/_extensions/file_browser/utils.lua
- lua/tests/make_entry_spec.lua
regression related to https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/368
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/370
> fix(make_entry): ordinal & display for higher depth search

- lua/telescope/_extensions/file_browser/make_entry_utils.lua
> fix: remove print

- README.md
Couldn't load config without these commas
> readme: fix setup example

- .github/workflows/docgen.yml
- .github/workflows/test.yml
- tweak docgen target
- add neovim 0.10 in test ci matrix
> chore: update ci

- .gitignore
- Makefile
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser.lua
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/picker.lua
- lua/telescope/_extensions/file_browser/utils.lua
- scripts/gendocs.lua
- scripts/minimal_init.vim
- deprecate `tree-sitter-lua` docgen for `docgen.nvim`
- update docs and add type annotations
- update ci config slightly
> docs: switch out docgen tools

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/lsp.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- scripts/gendocs.lua
will/do create/rename/delete request and notification support for related actions.
Only offered for nvim 0.10+.
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/396
> feat(lsp): add lsp file operations support

- README.md
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/405
> docs(README): incorrect setup table
