- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser.lua
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/picker.lua
* Consistent default keymappings between insert and normal mode
* Fix being unable to fully override (unmap) default keymappings
This partially solves #5 as now mappings can be fully unmapped and overriden at telescope setup. What's still not possible is unmapping when called interactively eg
```lua
require "telescope".extensions.file_browser.file_browser {
attach_mappings = function(prompt_bufnr, map)
map("i", "<C-f>", false)
return true
end
}
```
which seems to be an upstream issue.
In any case, I prefer having the default configuration in `pconf` and it should largely fix the issue.
@j-hui could you please test whether this works for you? Many thanks in advance!
> fix: keymapping defaults and overrides

- lua/telescope/_extensions/file_browser/finders.lua
Currently file_browser will always insert an "up dir" entry (../),
regardless of where it is in the filesystem
This change suppresses this entry if we are in the root directory (/)
Note I do not have access to Windows. I don't think \ is ever a
valid path in Windows, so don't believe this will have any adverse
affects on that OS, but I haven't been able to check specifically.
> fix: hide "../" when in root dir

- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/picker.lua
Ideally fixes #18 
@kascote could you please confirm whether this fixes your issue? The repro steps are incomplete since, if I understand correctly, you need to launch the file browser from a buffer within a sub-directory of `cwd` for the issue to occur as described.
> fix: results title on relative path

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser.lua
- lua/telescope/_extensions/file_browser/actions.lua
Adds selecting/toggling all entries and selecting all entries, with toggling all entries mappend by default to `<A-e>`
> feat: toggle all entries

- lua/telescope/_extensions/file_browser/actions.lua
`require("telescope.config").values.borderchars` returns a table with borderchars for preview, prompt and results, not some borderchars.
canceling `actions.rename_file()` was missing `return`
> fix: batch rename borderchars and calceling rename

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
Closes #29.
`respect_gitignore` reduces plenary.scandir performance
10x and therefore now is opt-in.
This will be eventually alleviated with an fd-based finder.
> fix: gitignore performance slowdown

- lua/telescope/_extensions/file_browser.lua
#31
When `defaults = { border = false }` selecting any directory results in an error
> fix: border = false error

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- scripts/gendocs.lua
Putting up the PR for users to see what'll land eventually.
Why is `fd` interesting?
* Speed: while `scandir` already is very fast, `fd` is faster and more importantly much, much more asyncish since it's off process
* `opts.depth=false` essentially acts as a mix of `find_{files, folders}`, extra speed may be worthwhile here
* Might be super cool to incorporate `--exec` (see `man fd`) in the future in some form (removing files by patterns etc. from within `nvim`)
> feat: fd file and folder finders

- .github/workflows/docgen.yml
- lua/telescope/_extensions/file_browser/actions.lua
This should check off the third item in the med priority list in #3.
I didn't see any instances of `./` showing up anywhere so I didn't really consider them. Really only looked at preventing `../` from being selected.
I also left references to `../` and `./` in the `ignore_values` but I can remove them if needed.
> fix: ignore '..' and '.' during select/toggle all

- lua/telescope/_extensions/file_browser/actions.lua
This commit refactors the user options from the previous style:
Remove Selected Files:
1: Yes
2: No
Type number and <Enter> or click with the mouse (q or empty cancels):
To a more user-friendly and intuitive format:
Remove selected files (Y/N):
Where the user can enter 'Y' or 'y' for 'Yes' and any other character
for 'No'.
> rfc: Remove selected files user options (#13)

- README.md
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
- lua/telescope/_extensions/file_browser/utils.lua
Closes #43 
Supersedes #44 
* Refactor redrawing border titles to a utility function, we can always redraw more than needed
* Introduce `cwd_to_path` option to hook `folder_browser` to `file_browser` path rather than neovim `cwd`
Maybe we can introduce actions to toggle between the two modes, but this should be a good start.
> feat: tie cwd of folder browser to file browser path

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
- lua/telescope/_extensions/file_browser/utils.lua
As per reddit request. This PR introduces the `grouped` option which initially groups entries in the `file_browser` by directory and files and only then sorts alphabetically. I would probably mark this optional as this is behavior that cannot be easily achieved with an `fd` finder, but happy to be convinced otherwise.
`fd` is required for `depth=false` and fast folder browsing. For classic `file_browser`, `plenary.scandir` is already plenty fast.
Before:
After
> feat: group dirs and files in file_browser

- lua/telescope/_extensions/file_browser/utils.lua
vim.loop.fs_stat returns nil when given an invalid file, e.g. a symlink with a non-existing target.
Fixes #70.
> Invalid files causes error when grouping is enabled.

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
Closes #78 
This commit enables creating, copying, and moving
files and folders from within folder_browser mode.
In doing so, the currently selected directory within
folder_browser serves as the target directory for the
corresponding telescope-file-browser action.
> feat: creating, copying & moving in folder_browser

- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/picker.lua
Adds new option `hide_parent_dir` (default false) to hide `../` in the file browser as it can be redundant to experienced users who use the `goto_parent_dir` action.
closes #93
> feat: add option `hide_parent_dir`

- lua/telescope/_extensions/file_browser/picker.lua
If the option is set to `true`, file browser will try to select the
current buffer at start. It has no effect if `opts.path` or `opts.cwd`
is not the parent directory of the current buffer or `opts.depth` is
greater than 1 or the initial mode is not `file`.
Closes #95
> close #95: add option `select_buffer`

- lua/telescope/_extensions/file_browser/actions.lua
win-32 always return 0 on windows as the correct check is win32. This fixes the problem I ran into with not being able to use the open function
> Fixes problem with using the wrong check to determine if on Windows or not

- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
- lua/telescope/_extensions/file_browser/utils.lua
Telescope allows the user to specify "prompt_title" and "results_title". I was making a theme and used those values to have custom titles which works fine for the default finders, but not for this one because the titles change upon changing directory. This fix prevents "fb_utils.redraw_border_title" from overwriting the titles if they are custom.
> fix: preserve custom titles

- lua/telescope/_extensions/file_browser.lua
Closes #114
cc @danielnehrig this also might be something you're looking for
This PR enables creating a file or folder in file browser mode on select default (i.e. `Enter`) whenever a prompt does not yield a result (i.e. results are empty). For the time being, this is the new default behavior, as 99% of cases users shouldn't be hitting enter randomly on empty results.
If anyone ever complains, feel free to provide a PR with possibility to opt out :) I just wanted to have fun with a quick & cool feature. Enabling opting out is the not so fun part :sweat_smile: 
Showcase
https://user-images.githubusercontent.com/39233597/160089672-3d62abc7-6949-43f9-ab02-39ff1ae217ef.mp4
> feat: create & open file/folder from prompt if results empty

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/picker.lua
The size and last changed date are now shown by default. Please see :h fb_picker.file_browser for more information.
The actions to sort by size or date are not yet mapped by default but users can do so via fb_actions.sort_by_{date, size}. I might add default mappings for them eventually.
https://user-images.githubusercontent.com/39233597/164119199-f63e3be1-ea1a-46fc-bfd5-81061159714a.mp4
creds to Conni for the low-level stuff to extract the info nicely formatted from the stat :)
> feat: size/date & sorting

- .github/workflows/docgen.yml
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser.lua
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/picker.lua
- lua/telescope/_extensions/file_browser/utils.lua
Continuation of #72
Closes #91 #87 
Changelog:
- Use `vim.ui.input` and `vim.notify` everywhere
- Smoothly pretty much all `hit-enter prompt`s by `redraw` on `vim.ui.input` with default `vim.notify` and casting all messages on a single line (probably not amazing if tons of single files/folders are created/deleted/etc. but can deal with it later)
- Introduce `quiet` option to suppress all outputs 
- Refactoring a proper config module
- Disallow removing parent folder (`file_browser`) and current folder (`folder_browser`) (yes, I've done something like that accidentally in my testing.. all my lua repos had to be restored via timeshift haha)
Since it is a very large PR, I apologize in before for any regression caused :) In my testing I couldn't find any, I've been on this branch some time …
> feat: notify and vim.ui harmonization

- lua/telescope/_extensions/file_browser/actions.lua
Closes #127 
Tab completion now completes the file path in `fb_actions.{create, rename, copy}`, the latter of which applies when attempting to possibly overwrite a file.
> feat: enable tab file completion for vim.ui.input

- lua/telescope/_extensions/file_browser.lua
Currently, using the non-default picker theme won't pass your defaults through correctly forcing the plugin defaults to be used.
> fix: pass defaults thru theme

- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
Unlike `fd` or `plenary`, `fb_actions.goto_{...}` appended an os separator the quick ordinal derivation did not account for.
Now, that's both unified -- the actions don't append a separator and the entry maker accounts for maybe having a separator appended to the cwd.
Closes #138
> fix(entry_maker): regression with trailng os separator in dirs

- lua/telescope/_extensions/file_browser/make_entry.lua
Adds handling around if entry.stat doesn't exist, additionally logs out that the file is missing.
> Added different formatting option for missing stat

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/picker.lua
There's been several requests of launching `file_browser` on `VimEnter` over netwr. I was initially skeptical of implementing this but considering this plugin is somewhat an alternative to file browsers/explorers/trees like [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua) and seeing as how they've implemented it, I thought why not. At least as an opt-in feature.
I can add some notes in the docs/readme but I wanted to get some thoughts on the idea as well as the potentially over-simplistic implementation of it.
> feat: enable hijacking of netrw on vim startup

- lua/telescope/_extensions/file_browser/config.lua
Prevents extra buffers being left that have the name of an opened directory.
@jamestrew
> hijack netrw - wipe the buffer matching the directory name

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
With { collapse_dirs = true }
going from (example from stow)
`dotfiles/`
to
`dotfiles/nvim/.config/nvim/`
only requires selecting nvim
in `file_browser` as intermediate
single-folder levels are skipped.
This also works in the reverse
direction.
Closes #158 
@cc paul-ohl
Could you please test this PR with your config? :) just making sure it doesn't result in unintended infinite loops for someone other than me :laughing:
> feat(file_browser): collapse dirs

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/picker.lua
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/152
> fix: typo in documentation

- lua/telescope/_extensions/file_browser/actions.lua
Currently, if there is at least 1 entry where `vim.loop.fs_stat` fails, all the other entries can't be sorted.
With this fix I can now sort entries as entries with `stat=false` are ignored in sorting.
To reproduce:
```bash
cd /tmp && mkdir deadsym & cd deadsym
ln -s /tmp/nonexistent/file file
nvim -c 'Telescope file_browser'
```
```
E5108: Error executing lua ....nvim/lua/telescope/_extensions/file_browser/actions.lua:666: attempt to index field 'stat' (a boolean val
ue)                                                                                                                                     
stack traceback: …
```
> fix: sort actions handle entries with no stat

- lua/telescope/_extensions/file_browser/finders.lua
fd on Windows outputs file paths with forward slashes when run under mingw. This ensures that fd always outputs backslashes on Windows systems. This should have no impact on other OSes.
Fix: https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/167
> fix(file_bowser): correct path separators on mingw

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/make_entry.lua
Neovim now has `setcellwidths()` ([doc][]) and we can set arbitrary codepoint to `1` or `2` widths despite of the `'ambiwidth'` setting.
[doc]: https://neovim.io/doc/user/builtin.html#setcellwidths()
I set devicon's glyphs can have `2` widths and found all icons become `…` characters. This patch enables to change this for such cases.
| before | after |
|--|--|
| <img width="353" alt="スクリーンショット 0004-08-18 14 50 06" src="https://user-images.githubusercontent.com/1239245/185304085-5cd420ca-a8e6-420c-bdb3-4a652ae50d2a.png"> | <img width="366" alt="スクリーンショット 0004-08-18 14 51 19" src="https://user-images.githubusercontent.com/1239245/185304116-683180dc-d84f-4a93-862f-8240ed6164cd.png"> |
> Enable to change icon width

- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
netrw handles opening of urls via an autcmd when doing `nvim <url>` or `:e <url>`.
Disabling netrw entirely when `hijack_netrw = true` had the unintended side effect of breaking the above mentioned feature so I'm removing the disabling of netrw.
Closes #149
> fix: allow netrw to handle url openings when `hijack_netrw = true`

- lua/telescope/_extensions/file_browser/config.lua
Wrap expand in pcall as it seemingly
does not exist in scenarios for which
file-browser should not be opened anyways.
Closes #179
> fix(hijack_netrw): alternate file may not exist

- .github/workflows/lint.yml
- lua/telescope/_extensions/file_browser/config.lua
- scripts/gendocs.lua
problem: netrw may (or may not be) sourced before
telescope-file-browser configuration.
Therefore "FileExplorer" augroup may not
be cleared and not get set appropriately
solution: clear FileExplorer appropriately and
create new augroup for telescope-file-browser
closes #182 
@qRoC could you please test whether it fixes the issue for you?
> fix(hijack_netrw): netrw telescope-file-browser entanglement

- lua/telescope/_extensions/file_browser/make_entry.lua
Thanks for all your work on this plugin! I've been using this for a while now, and I have a minor usability suggestion:
Every time I open `telescope-file-browser` in a directory with a broken symlink, the logger raises a warning, which might be a bit unnecessary. Plus now with `vim.o.cmdheight = 0`, this results in needing to press `<Enter>` again to clear the logger warning before using the file browser. 
I suggest just adding one more `if` statement to check if it's a link, and not to send through a warning to the logger if that's the case. If `fs_lstat()` returns an invalid result, then raise the warning as before.
A quick demo after running `:!ln -s /tmp/this/doesnt/exist ./broken_link`:
No stats or file preview are displayed for the broken link, and the logger is silent because this …
> feat: supress warning if a broken link is found

- lua/telescope/_extensions/file_browser/actions.lua
Should be `actions.remove`, not `actions.move`.
> fix(fb_actions.remove): fix incorrect log message prefix

- lua/telescope/_extensions/file_browser/make_entry.lua
Fixes regression bug related to #208.
When `grouped = true`, the entries passed to `make_entry` don't have a os separator at the end.
This was resulting in directories being displayed like so with the last letter being truncated:
> fix(make_entry): path display truncates directory when `grouped = true`

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
sync fd speeds up browsing with
- grouped, gitignore, autodepth etc.
+ Deactivate grouped for auto_depth, really gets in the way with half-way larger projects
> feat(file_browser): sync fd for faster support of flags

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
Allows users to disable the usage of `fd` for whatever reason (compatibility issues, etc) through a new `use_fd` option. Default is set to `true`. Closes #212 
I've also been considering adding unit tests for the picker/finders and having an option to disable `fd` will make testing setup easier.
> feat: add option `use_fd` to selectively use `fd`

- README.md
- lua/telescope/_extensions/file_browser/make_entry.lua
When `nvim-web-devicons` is not installed, entries for files fail to compensate for the icon width of directories causing misalignment of the entries for files compared to that of folders.
Before:
After:
> fix: entry misalignment with no devicons

- lua/telescope/_extensions/file_browser/make_entry.lua
Closes #230 
@fdschmidt93 Nsing the `TelescopePreviewDirectory` hl for directory entries.
This will actually bring parity in how directories are displayed between the entries, file preview and even netrw's explorer.
I think this change is reasonable enough to make it a default behavior without adding any new options.
> feat: add directory hl for directory entries

- .luarc.json
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/git.lua
- lua/tests/fb_git_spec.lua
Change `git status --short -- . ` -> `git status --porcelain -- .`
The `porcelain` flag produces output more suited for consumption by scripts.
> Give the output in an easy-to-parse format for scripts. This is similar to the short output, but will remain stable across Git versions and regardless of user configuration.
This will avoid issues like https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/243
To accommodate this change `fb_git.parse_status_output` now takes the cwd of the picker as opposed to the `path`.
> fix(git): git status use `porcelain` flag

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
- lua/telescope/_extensions/file_browser/utils.lua
If enabled, will update the prompt with the relative path from the CWD. Defaults to `false`
> Add 'path_prompt_prefix' option

- README.md
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/picker.lua
I noticed that the order of the columns was being shuffled every time you restart neovim, so I changed the iterator slightly so the order is consistent every time. 
I also added `entry.lstat` to be able to accurately display if a fd is a symlink or not, since `stat` _follows_ links.
Finally, `@` is appended to flagged fd's.
> Add file-descriptor mode column

- README.md
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/picker.lua
This one is pretty simple, and if I'm being honest, stolen straight from emacs' `dired`:
In insert mode, If the prompt is empty and the user types `<bs>`, go to parent dir. If there _is_ any user input in the prompt, then behave as normal. 
This pairs very nicely with the new path_prompt feature.
https://user-images.githubusercontent.com/7228095/227717450-1113e881-4eca-4a0f-b0e8-1ac2b9f587a9.mov
> Add action "backspace" for insert mode.

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/utils.lua
Using the `goto_parent_dir` action will now set the picker selection to the directory you just left. 
Additionally, I made a slight refactor/fix so that when you create a directory using the `create` action, the selection is set to the newly created directory. Previously, this was only working for created files.
I have tested these changes against all other actions involving files and folders, and everything works fine except for the `copy` action, which is also broken on the master as well I think
> feat(actions): goto_parent_dir selection original dir entry

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/make_entry.lua
Fixes a small error in the entry width calculation related to the separator width.
This was leading to ever worsening trailing spaces at the end of entries as we add more `display_stat` items.
Before:
After (with fix):
(btw experimenting with adding owner/group fs_stat info but the width can't be static due to non-deterministic username lengths so not super simple - maybe not worth it)
I've tested this using a mix both options for `git_status` and `disable_devicons` and looks good.
> fix: entry width calculation with separator

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
Currently, creating a nested file structure doesn't move your selection to the root of the newly created file (eg. `./create/new/file.txt` doesn't move the selection to `./create/`).
This PR will address this. As long as the newly created file/folder is within the cwd, the entry selection will move to the root of the newly created object.
> fix: creating nested files moves selection to file ancestor

- lua/telescope/_extensions/file_browser/git.lua
- lua/tests/fb_git_spec.lua
Currently renamed/copied status are not being correctly parsed.
```
R lua/telescope/_extensions/file_browser/stats.lua -> lua/telescope/_extensions/file_browser/fs_stat.lua
```
> fix(git): correctly parse and render renamed/copied status

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
Modifies the `hidden` option to support separate `hidden` option for file/folder browser.
```
hidden table|boolean: determines whether to show hidden files or not (default: `{ file_browser = false, folder_browser = false }`)
```
closes #227
> feat: separate hidden opts for file/folder browser

- lua/telescope/_extensions/file_browser/actions.lua
the '+' icon not updated when select_all/toggle_all
solution found in [telescope.nvim #1682](https://github.com/nvim-telescope/telescope.nvim/pull/1682), works for me.
> fix(action): update multi_icon with select/toggle_all actions

- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
prevents hard error when trying to enter ("cd" into) directory with no execute permission
> fix: prevent disallowed directory access

- lua/telescope/_extensions/file_browser/make_entry.lua
Accessing of `stat` and `lstat` properties on entries were previously handled poorly leading to stack overflow issues when `fs_stat` and `fs_lstat` returned nothing. This seems to be not an uncommon event on Windows.
One part of the puzzle for #285
> fix(make_entry): handle lstat access

- lua/telescope/_extensions/file_browser/finders.lua
removes the `--base-directory` flag usage and instead passes the cwd for the fd command to job runners.
debian/ubuntu (and other related distros) ship fd version 7.4.0 which doesn't support the `--base-directory` flag.
closes #297
> remove `--base-directory` fd flag for better compatibility

- lua/telescope/_extensions/file_browser/finders.lua
Go back to letting git status command silently error.
Otherwise it loudly errors when given path is not inside a git repo.
fixes #301
> feat(git): error handling when not inside git repo

- lua/telescope/_extensions/file_browser/finders.lua
parse `git status --porcelain -- .` based on git toplevel directory stored in new field `git_root`.
closes #309
> fix(git): show status after `cd`

- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/picker.lua
What the title says - allow users to use the oldschool input methods. IMO, much nicer, and the confirm() function doesn't require pressing `<cr>`, which is a win.
Default setting is left as-is.
> Allow users to use vim.fn.input() and vim.fn.confirm() instead of vim.ui.input()

- lua/telescope/_extensions/file_browser/make_entry.lua
use `os_sep`(`require("plenary.path").path.sep`), instead of `/`
> fix: incorrect path separator of "../" on Windows

- README.md
- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
Adds a new `no_ignore` option (only applicable to fd) which enables fd's `--no-ignore` option
closes #326
> feat: add `no_ignore` option for fd

- lua/telescope/_extensions/file_browser/config.lua
closes #321
wraps the default `attach_mapping` with provided `attach_mappings`
> fix: augment `attach_mappings` without overwriting defaults

- lua/telescope/_extensions/file_browser/actions.lua
The `path_separator` action working in the `folder_browser` is probably not the expected behavior since path separators are valid (and arguably common) tokens for searches in this mode.
> fix(folder_browser): disable path_separator action

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/actions.lua
Wild that this bug is on `master` since initial commit.
I had this fixed on the `tree` branch (with a slight, unrelated bug).
Problem: open buffers are not correctly renamed when their parent(s) directories or the buffer itself is moved.
Solution: rename moved buffers
Add note on order sensitivity. Maybe we should not allow unpacking, but then we would have to recursively check whether any parent is included.
> fix(actions.move): correctly rename open (dir) buffers

- lua/telescope/_extensions/file_browser/actions.lua
`vim.fs.basename("/foo/bar/)` returns an empty string. This behavior differs from the unix `basename` program which returns `bar`.
Just need to accommodate for this.
> fix(action.move): moving folders

- lua/telescope/_extensions/file_browser/actions.lua
This reverts commit 98101b22402cd6d1c7e9a7e0c4718bfc98cb1625.
See: https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/342#issuecomment-1844091746
> Revert "fix(action.move): moving folders (#342)"

- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/git.lua
Need to compute the git toplevel directory upon changing directories since calling `git status` inside a git submodule will give the status relative to the toplevel directory of the submodule, not the parent toplevel directory. This was causing a bug with bad paths being created for git status changes in submodules.
closes #353
> fix(git): show status for git submodules

- lua/telescope/_extensions/file_browser/actions.lua
- lua/telescope/_extensions/file_browser/make_entry.lua
- lua/telescope/_extensions/file_browser/utils.lua
`plenary.scan_dir`, unlike `fd` doesn't append trailing path separators to directory paths. This was leading to inconsistent behaviors getting the basename of directories depending on the usage of scan_dir/fd.
This PR refactors the entry maker to standardizes path strings to NOT end with path separators regardless of type. This is inline with `fs_realpath` and more compatible with `vim.fs` functions.
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/357
> fix(actions.move): `scan_dir` folding moving

- lua/telescope/_extensions/file_browser/actions.lua
plenary's default for some reason is 0700.
Changing ours to 0755 to be more consistent with `mkdir` which is also the default for `fs_mkdir` (via `mkdir`).
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/360
> fix(actions.create): use default mkdir mode 0755

- lua/telescope/_extensions/file_browser/utils.lua
Doing `:Telescope file_browser path=/path/to/some/file.txt` now throws an optional warning (based on "quiet" option) and just opens in file_browser in the cwd.
> fix(picker): reject non-dir path option

- lua/telescope/_extensions/file_browser/make_entry.lua
extra os_sep was causing a bad basename.
eg `/tmp//foo` was turning into `oo`
closes https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/349
> fix(make_entry): fix ordinal basename

- README.md
Need 0.9.0 or higher for `vim.fs` access.
> docs(readme): add neovim minimum version

- .github/workflows/docgen.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- .gitignore
- Makefile
- lua/telescope/_extensions/file_browser/utils.lua
- lua/tests/fb_git_spec.lua
- lua/tests/make_entry_spec.lua
- scripts/minimal_init.vim
- Add testing github actions workflow
- Tweak docgen workflow so it's easier to do locally
> build: rework ci actions

- README.md
- lua/telescope/_extensions/file_browser/utils.lua
Added a concrete example of the alternative approach via lua.
> Updated Readme

- doc/telescope-file-browser.txt
- lua/telescope/_extensions/file_browser/config.lua
- lua/telescope/_extensions/file_browser/finders.lua
- lua/telescope/_extensions/file_browser/picker.lua
Enables/disables the creation of files/folders from the prompt if no entry is selected.
Defaults to true to preserve existing behavior.
closes #381
> feat: add `create_from_prompt` option

- lua/telescope/_extensions/file_browser/finders.lua
`vim.fn.executable "fd"` takes up to one second, at least on WSL 2 + NixOS setup I'm using. In this PR I'm moving the invocation into a lazy function so that when the plugin is loaded at startup the user wouldn't incur this cost right away.
> fix: move has_fd check into a function to reduce startup time

- lua/telescope/_extensions/file_browser/lsp.lua
Now [will_do](https://github.com/nvim-telescope/telescope-file-browser.nvim/blob/a46780830b576049c675680650f773bedfa8677a/lua/telescope/_extensions/file_browser/lsp.lua#L170) can send `result.result=nil` to `vim.lsp.util.apply_workspace_edit` which expect not nil `WorkspaceEdit`. In some cases (for example when a rust analyzer is enabled) it leads to error.
Be [lsp spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_willRenameFiles) willRenameFiles can return an empty `result.result`. So I added handling of this case.  Also, it doesn't look like an error, so there is no error message.
> fix: handle willRenameFiles result.result nil

- lua/telescope/_extensions/file_browser/fs_stat.lua
- fixes: 'Warning: vim.tbl_flatten is deprecated, use vim.iter(…):flatten():totable() instead.'
- replaces usage of vim.tbl_flatten() while keeping backward compatibility for < v0.10.0.
fixes issue: #414
> fix: use vim.iter(...):flatten():totable()
